#use_frameworks!个别需要用到它，比如reactiveCocoa
platform :ios, '11.0'
use_frameworks!

target 'VeepooBleSDKDemo' do

#OC pod集成也是这样的

pod 'iOSDFULibrary', '~> 4.11.1’

pod 'FMDB'

pod 'AFNetworking', '~> 4.0'

pod 'MJExtension'

end

post_install do |installer|
  installer.generated_projects.each do |project|
    project.targets.each do |target|
            target.build_configurations.each do |config|
                config.build_settings['IPHONEOS_DEPLOYMENT_TARGET'] = '11.0'
            end
        end
    end
end
